# Generated by Django 5.2.5 on 2025-09-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_transaction_wallet_alter_transaction_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('dividend', 'Dividend')], max_length=15),
        ),
    ]
