# Generated by Django 5.2.5 on 2025-10-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        # Remover campo investment da tabela Transaction
        migrations.RemoveField(
            model_name='transaction',
            name='investment',
        ),
        # Tornar campo wallet obrigatório na tabela Transaction
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='transactions', to='finances.wallet'),
        ),
        # Remover tabela Investment
        migrations.DeleteModel(
            name='Investment',
        ),
        # Remover tabela Category
        migrations.DeleteModel(
            name='Category',
        ),
    ]
